export { default as Navbar } from './navbar/Navbar'
export { default as Hero } from './hero/Hero'
export { default as Features } from './features/Features'
export { default as Services } from './services/Services'
export { default as Main } from './main/Main'
export { default as Gallery } from './gallery/Gallery'
export { default as Offers } from './offers/Offers'
export { default as Build } from './build/Build'
export { default as Pricing } from './pricing/Pricing'
export { default as Contact} from './contact/Contact'
export { default as Footer} from './footer/Footer'